/* Generated By:JavaCC: Do not edit this line. MetricReaderTokenManager.java */
/* Copyright (c) 2014, Salesforce.com, Inc.
 * All rights reserved.
 *  
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 *   
 *      Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 *
 *      Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *      Neither the name of Salesforce.com nor the names of its contributors may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. */
package com.salesforce.dva.argus.service.metric;
import java.io.*;
import java.util.*;
import com.salesforce.dva.argus.entity.Metric;
import com.salesforce.dva.argus.service.DiscoveryService;
import com.salesforce.dva.argus.service.TSDBService;
import com.salesforce.dva.argus.service.metric.transform.Transform;
import com.salesforce.dva.argus.service.metric.transform.TransformFactory;
import com.salesforce.dva.argus.service.metric.transform.TransformIterator;
import com.salesforce.dva.argus.service.tsdb.MetricQuery;
import com.salesforce.dva.argus.service.tsdb.MetricQuery.Aggregator;
import com.salesforce.dva.argus.system.SystemAssert;
import com.salesforce.dva.argus.system.SystemException;
import com.google.inject.Inject;
import static com.salesforce.dva.argus.system.SystemAssert.*;

/** Token Manager. */
public class MetricReaderTokenManager implements MetricReaderConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0xffffffffff800000L) != 0L || (active1 & 0x3fffL) != 0L)
         {
            jjmatchedKind = 88;
            return 78;
         }
         return -1;
      case 1:
         if ((active0 & 0xffffffffff800000L) != 0L || (active1 & 0x3fffL) != 0L)
         {
            jjmatchedKind = 88;
            jjmatchedPos = 1;
            return 78;
         }
         return -1;
      case 2:
         if ((active0 & 0xfffffe7ff3800000L) != 0L || (active1 & 0x3fddL) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 88;
               jjmatchedPos = 2;
            }
            return 78;
         }
         if ((active0 & 0x1800c000000L) != 0L || (active1 & 0x22L) != 0L)
            return 78;
         return -1;
      case 3:
         if ((active0 & 0xc0000000c0000000L) != 0L || (active1 & 0x210L) != 0L)
            return 78;
         if ((active0 & 0x3ffffe7f3b800000L) != 0L || (active1 & 0x3dcdL) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 88;
               jjmatchedPos = 3;
            }
            return 78;
         }
         return -1;
      case 4:
         if ((active0 & 0x303e400e08000000L) != 0L || (active1 & 0x40L) != 0L)
            return 78;
         if ((active0 & 0x8fc1be71b3800000L) != 0L || (active1 & 0x3d8dL) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 88;
               jjmatchedPos = 4;
            }
            return 78;
         }
         return -1;
      case 5:
         if ((active0 & 0x8800800b0000000L) != 0L || (active1 & 0x1L) != 0L)
            return 78;
         if ((active0 & 0x8741b67d03800000L) != 0L || (active1 & 0x3d8cL) != 0L)
         {
            if (jjmatchedPos != 5)
            {
               jjmatchedKind = 88;
               jjmatchedPos = 5;
            }
            return 78;
         }
         return -1;
      case 6:
         if ((active0 & 0x8041bc6923800000L) != 0L || (active1 & 0x358cL) != 0L)
         {
            if (jjmatchedPos != 6)
            {
               jjmatchedKind = 88;
               jjmatchedPos = 6;
            }
            return 78;
         }
         if ((active0 & 0x700021400000000L) != 0L || (active1 & 0x800L) != 0L)
            return 78;
         return -1;
      case 7:
         if ((active0 & 0x202123800000L) != 0L)
            return 78;
         if ((active0 & 0x80419e4800000000L) != 0L || (active1 & 0x358cL) != 0L)
         {
            if (jjmatchedPos != 7)
            {
               jjmatchedKind = 88;
               jjmatchedPos = 7;
            }
            return 78;
         }
         return -1;
      case 8:
         if ((active0 & 0x41800000000000L) != 0L || (active1 & 0x100L) != 0L)
            return 78;
         if ((active0 & 0x80001e4801000000L) != 0L || (active1 & 0x348cL) != 0L)
         {
            if (jjmatchedPos != 8)
            {
               jjmatchedKind = 88;
               jjmatchedPos = 8;
            }
            return 78;
         }
         return -1;
      case 9:
         if ((active0 & 0x80011a0801000000L) != 0L || (active1 & 0x3400L) != 0L)
         {
            jjmatchedKind = 88;
            jjmatchedPos = 9;
            return 78;
         }
         if ((active0 & 0x44000000000L) != 0L || (active1 & 0x8cL) != 0L)
            return 78;
         return -1;
      case 10:
         if ((active0 & 0x1000800000000L) != 0L || (active1 & 0x1400L) != 0L)
            return 78;
         if ((active0 & 0x80001a0001000000L) != 0L || (active1 & 0x2000L) != 0L)
         {
            jjmatchedKind = 88;
            jjmatchedPos = 10;
            return 78;
         }
         return -1;
      case 11:
         if ((active0 & 0x20000000000L) != 0L || (active1 & 0x2000L) != 0L)
            return 78;
         if ((active0 & 0x8000180001000000L) != 0L)
         {
            jjmatchedKind = 88;
            jjmatchedPos = 11;
            return 78;
         }
         return -1;
      case 12:
         if ((active0 & 0x8000100001000000L) != 0L)
         {
            jjmatchedKind = 88;
            jjmatchedPos = 12;
            return 78;
         }
         if ((active0 & 0x80000000000L) != 0L)
            return 78;
         return -1;
      case 13:
         if ((active0 & 0x8000000000000000L) != 0L)
            return 78;
         if ((active0 & 0x100001000000L) != 0L)
         {
            jjmatchedKind = 88;
            jjmatchedPos = 13;
            return 78;
         }
         return -1;
      case 14:
         if ((active0 & 0x100001000000L) != 0L)
         {
            jjmatchedKind = 88;
            jjmatchedPos = 14;
            return 78;
         }
         return -1;
      case 15:
         if ((active0 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 88;
            jjmatchedPos = 15;
            return 78;
         }
         if ((active0 & 0x100000000000L) != 0L)
            return 78;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 13:
         jjmatchedKind = 3;
         return jjMoveStringLiteralDfa1_0(0x10L, 0x0L);
      case 40:
         return jjStopAtPos(0, 82);
      case 41:
         return jjStopAtPos(0, 83);
      case 44:
         return jjStopAtPos(0, 79);
      case 58:
         return jjStopAtPos(0, 78);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x10621000000000L, 0x0L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x20000000000000L, 0x0L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x4000000000000L, 0x40cL);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x40f0000000L, 0x180L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x100000000000000L, 0x0L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0xc000000000000000L, 0x1L);
      case 71:
         return jjMoveStringLiteralDfa1_0(0x8000000000000L, 0x0L);
      case 72:
         return jjMoveStringLiteralDfa1_0(0x400000003000000L, 0x3000L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x200002000800000L, 0x0L);
      case 74:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200L);
      case 76:
         return jjMoveStringLiteralDfa1_0(0x1800000000000000L, 0x2L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x80098100000000L, 0x0L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x1800000000000L, 0x0L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x40040000000000L, 0x20L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x2000000000000000L, 0x0L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0xe0c000000L, 0x50L);
      case 85:
         return jjMoveStringLiteralDfa1_0(0x2000000000000L, 0x0L);
      case 90:
         return jjMoveStringLiteralDfa1_0(0x100000000000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800L);
      case 123:
         return jjStopAtPos(0, 80);
      case 125:
         return jjStopAtPos(0, 81);
      default :
         return jjMoveNfa_0(2, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 10:
         if ((active0 & 0x10L) != 0L)
            return jjStopAtPos(1, 4);
         break;
      case 57:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x20L);
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000010000000000L, active1, 0L);
      case 66:
         return jjMoveStringLiteralDfa2_0(active0, 0x10200000000000L, active1, 0L);
      case 67:
         return jjMoveStringLiteralDfa2_0(active0, 0xe00000000L, active1, 0L);
      case 68:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000L, active1, 0L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x20144003000000L, active1, 0x100L);
      case 72:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x40L);
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0xd4000080f0000000L, active1, 0x1L);
      case 76:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000000L, active1, 0L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x202002000000000L, active1, 0L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x885880000000000L, active1, 0x692L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x48000000000000L, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x10c000000L, active1, 0xcL);
      case 86:
         return jjMoveStringLiteralDfa2_0(active0, 0x21000000000L, active1, 0L);
      case 87:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x3000L);
      case 88:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x800L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 48:
         if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(2, 69, 78);
         break;
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0xe00000000L, active1, 0L);
      case 67:
         return jjMoveStringLiteralDfa3_0(active0, 0x300000000000000L, active1, 0L);
      case 69:
         return jjMoveStringLiteralDfa3_0(active0, 0x21000800000L, active1, 0L);
      case 70:
         return jjMoveStringLiteralDfa3_0(active0, 0xc0000000L, active1, 0L);
      case 71:
         if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(2, 65, 78);
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000000000L, active1, 0L);
      case 73:
         return jjMoveStringLiteralDfa3_0(active0, 0x2400003000000L, active1, 0x240L);
      case 76:
         return jjMoveStringLiteralDfa3_0(active0, 0xc020000100000000L, active1, 0xdL);
      case 77:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000008000000L, active1, 0L);
      case 78:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 39, 78);
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000000000L, active1, 0x400L);
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x58000000000000L, active1, 0L);
      case 82:
         return jjMoveStringLiteralDfa3_0(active0, 0x1944000000000L, active1, 0x10L);
      case 83:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000L, active1, 0L);
      case 84:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000L, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000000L, active1, 0L);
      case 86:
         return jjMoveStringLiteralDfa3_0(active0, 0x80080030000000L, active1, 0x100L);
      case 87:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000000000L, active1, 0x80L);
      case 88:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 40, 78);
         break;
      case 95:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x3000L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x800L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000000L, active1, 0L);
      case 67:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000000L, active1, 0L);
      case 68:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x2000L);
      case 69:
         return jjMoveStringLiteralDfa4_0(active0, 0x800002000000000L, active1, 0L);
      case 70:
         if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 30;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000L, active1, 0x1040L);
      case 71:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000000000L, active1, 0L);
      case 72:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000000000L, active1, 0L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0x1080084030000000L, active1, 0x100L);
      case 76:
         if ((active0 & 0x4000000000000000L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x8300000e00000000L, active1, 0xcL);
      case 77:
         return jjMoveStringLiteralDfa4_0(active0, 0x1800003000000L, active1, 0L);
      case 78:
         if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(3, 73, 78);
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000800000L, active1, 0x80L);
      case 79:
         return jjMoveStringLiteralDfa4_0(active0, 0x22300000000000L, active1, 0L);
      case 80:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000000000L, active1, 0L);
      case 82:
         return jjMoveStringLiteralDfa4_0(active0, 0x21000000000L, active1, 0L);
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x400L);
      case 84:
         if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(3, 68, 78);
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000L, active1, 0x1L);
      case 85:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000000L, active1, 0L);
      case 86:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000000000L, active1, 0L);
      case 95:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x800L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa5_0(active0, 0x41821000000000L, active1, 0x100L);
      case 68:
         return jjMoveStringLiteralDfa5_0(active0, 0x33000000L, active1, 0L);
      case 69:
         if ((active0 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 52, 78);
         else if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 61, 78);
         return jjMoveStringLiteralDfa5_0(active0, 0x400040c00000000L, active1, 0x2401L);
      case 71:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000L, active1, 0L);
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x100100000000L, active1, 0L);
      case 76:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000000L, active1, 0L);
      case 78:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 49, 78);
         return jjMoveStringLiteralDfa5_0(active0, 0x80080000000000L, active1, 0L);
      case 79:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x1000L);
      case 80:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 51, 78);
         break;
      case 83:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 46, 78);
         return jjMoveStringLiteralDfa5_0(active0, 0x800000000000000L, active1, 0x80L);
      case 84:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 50, 78);
         else if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 60, 78);
         else if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(4, 70, 78);
         return jjMoveStringLiteralDfa5_0(active0, 0x800000L, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa5_0(active0, 0x300000000000000L, active1, 0L);
      case 86:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 27, 78);
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000L, active1, 0L);
      case 87:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 53, 78);
         break;
      case 95:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000080000000L, active1, 0xcL);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x800L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1);
      return 5;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa6_0(active0, 0x4003000000L, active1, 0x84L);
      case 66:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x8L);
      case 67:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000000000L, active1, 0x400L);
      case 68:
         return jjMoveStringLiteralDfa6_0(active0, 0x300000000000000L, active1, 0L);
      case 69:
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 28;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000L, active1, 0L);
      case 70:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000000L, active1, 0L);
      case 71:
         if ((active0 & 0x80000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x400a1000000000L, active1, 0L);
      case 73:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000L, active1, 0L);
      case 76:
         return jjMoveStringLiteralDfa6_0(active0, 0x1800000000000L, active1, 0L);
      case 78:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000000L, active1, 0L);
      case 80:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000L, active1, 0L);
      case 82:
         if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(5, 64, 78);
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000L, active1, 0x1000L);
      case 83:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000000000L, active1, 0L);
      case 84:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 59, 78);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x100L);
      case 85:
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000000L, active1, 0L);
      case 86:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(5, 31, 78);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x2000L);
      case 95:
         return jjMoveStringLiteralDfa6_0(active0, 0xc00000000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x800L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1);
      return 6;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa7_0(active0, 0x8040082000000000L, active1, 0L);
      case 66:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x4L);
      case 69:
         if ((active0 & 0x1000000000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 6;
         }
         else if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 56, 78);
         else if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 57, 78);
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000000L, active1, 0x1008L);
      case 73:
         return jjMoveStringLiteralDfa7_0(active0, 0x1800000000000L, active1, 0x2100L);
      case 76:
         return jjMoveStringLiteralDfa7_0(active0, 0x103000000L, active1, 0L);
      case 77:
         return jjMoveStringLiteralDfa7_0(active0, 0x100800000000L, active1, 0x80L);
      case 84:
         if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 58, 78);
         return jjMoveStringLiteralDfa7_0(active0, 0x244000800000L, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x400L);
      case 86:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(6, 34, 78);
         break;
      case 95:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000L, active1, 0L);
      case 104:
         if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(6, 75, 78);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1);
      return 7;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa8_0(active0, 0x800000000L, active1, 0x2000L);
      case 66:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000000L, active1, 0L);
      case 67:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x1000L);
      case 69:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 45, 78);
         break;
      case 73:
         return jjMoveStringLiteralDfa8_0(active0, 0x144000000000L, active1, 0L);
      case 76:
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 25;
            jjmatchedPos = 7;
         }
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 37, 78);
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000001000000L, active1, 0x8L);
      case 79:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x104L);
      case 80:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x80L);
      case 84:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000000000L, active1, 0x400L);
      case 86:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(7, 29, 78);
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000000L, active1, 0L);
      case 89:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(7, 23, 78);
         else if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(7, 32, 78);
         break;
      case 90:
         return jjMoveStringLiteralDfa8_0(active0, 0x1800000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1);
      return 8;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x1000L);
      case 67:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000000000000000L, active1, 0L);
      case 69:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 8;
         }
         else if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 54, 78);
         return jjMoveStringLiteralDfa9_0(active0, 0x10a0000000000L, active1, 0L);
      case 73:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x400L);
      case 76:
         return jjMoveStringLiteralDfa9_0(active0, 0x40000000000L, active1, 0x80L);
      case 78:
         if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(8, 72, 78);
         break;
      case 79:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x8L);
      case 83:
         return jjMoveStringLiteralDfa9_0(active0, 0x100000000000L, active1, 0L);
      case 84:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000000L, active1, 0x2000L);
      case 86:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000000000L, active1, 0x4L);
      case 95:
         return jjMoveStringLiteralDfa9_0(active0, 0x1000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1);
      return 9;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa10_0(active0, 0x800000000L, active1, 0L);
      case 69:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 38, 78);
         else if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 42, 78);
         else if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(9, 66, 78);
         else if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(9, 71, 78);
         break;
      case 73:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x2000L);
      case 76:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000000000L, active1, 0L);
      case 82:
         return jjMoveStringLiteralDfa10_0(active0, 0x80000000000L, active1, 0L);
      case 83:
         return jjMoveStringLiteralDfa10_0(active0, 0x100000000000L, active1, 0x1000L);
      case 84:
         return jjMoveStringLiteralDfa10_0(active0, 0x1000000L, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa10_0(active0, 0x8000000000000000L, active1, 0L);
      case 86:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x400L);
      case 87:
         if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(9, 67, 78);
         break;
      case 95:
         return jjMoveStringLiteralDfa10_0(active0, 0x1000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(8, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, active1);
      return 10;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa11_0(active0, 0x80000000000L, active1, 0L);
      case 69:
         if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(10, 74, 78);
         break;
      case 72:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(10, 35, 78);
         break;
      case 73:
         return jjMoveStringLiteralDfa11_0(active0, 0x100000000000L, active1, 0L);
      case 76:
         return jjMoveStringLiteralDfa11_0(active0, 0x8000000000000000L, active1, 0L);
      case 79:
         return jjMoveStringLiteralDfa11_0(active0, 0x20001000000L, active1, 0x2000L);
      case 84:
         if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(10, 76, 78);
         break;
      case 86:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 48, 78);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0, active1);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(9, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, active1);
      return 11;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa12_0(active0, 0x8000000000000000L, active1, 0L);
      case 71:
         return jjMoveStringLiteralDfa12_0(active0, 0x80000000000L, active1, 0L);
      case 78:
         if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(11, 77, 78);
         return jjMoveStringLiteralDfa12_0(active0, 0x100000000000L, active1, 0L);
      case 84:
         return jjMoveStringLiteralDfa12_0(active0, 0x1000000L, active1, 0L);
      case 87:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(11, 41, 78);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, active0, active1);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(10, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, 0L);
      return 12;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa13_0(active0, 0x1000000L);
      case 69:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 43, 78);
         break;
      case 71:
         return jjMoveStringLiteralDfa13_0(active0, 0x100000000000L);
      case 84:
         return jjMoveStringLiteralDfa13_0(active0, 0x8000000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0, 0L);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0, 0L);
      return 13;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(13, 63, 78);
         break;
      case 76:
         return jjMoveStringLiteralDfa14_0(active0, 0x1000000L);
      case 83:
         return jjMoveStringLiteralDfa14_0(active0, 0x100000000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0, 0L);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0, 0L);
      return 14;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa15_0(active0, 0x1000000L);
      case 85:
         return jjMoveStringLiteralDfa15_0(active0, 0x100000000000L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0, 0L);
}
private int jjMoveStringLiteralDfa15_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0, 0L);
      return 15;
   }
   switch(curChar)
   {
      case 77:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(15, 44, 78);
         break;
      case 86:
         return jjMoveStringLiteralDfa16_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0, 0L);
}
private int jjMoveStringLiteralDfa16_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0, 0L);
      return 16;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(16, 24, 78);
         break;
      default :
         break;
   }
   return jjStartNfa_0(15, active0, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 78;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 78:
                  if ((0x83ffe40000000000L & l) != 0L)
                     jjCheckNAddTwoStates(71, 72);
                  else if (curChar == 61)
                     jjCheckNAdd(73);
                  if ((0x83ffe40000000000L & l) != 0L)
                  {
                     if (kind > 89)
                        kind = 89;
                     jjCheckNAdd(70);
                  }
                  if ((0x83ffe40000000000L & l) != 0L)
                  {
                     if (kind > 88)
                        kind = 88;
                     jjCheckNAdd(69);
                  }
                  break;
               case 2:
                  if ((0x83ffe40000000000L & l) != 0L)
                  {
                     if (kind > 88)
                        kind = 88;
                     jjCheckNAddStates(0, 3);
                  }
                  else if (curChar == 36)
                     jjCheckNAdd(15);
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 85)
                        kind = 85;
                     jjCheckNAddStates(4, 6);
                  }
                  else if (curChar == 45)
                     jjCheckNAddTwoStates(62, 64);
                  break;
               case 14:
                  if (curChar == 36)
                     jjCheckNAdd(15);
                  break;
               case 15:
                  if ((0x83ffe40000000000L & l) == 0L)
                     break;
                  if (kind > 91)
                     kind = 91;
                  jjCheckNAdd(15);
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 85)
                     kind = 85;
                  jjCheckNAddStates(4, 6);
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 85)
                     kind = 85;
                  jjCheckNAdd(30);
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(31, 32);
                  break;
               case 33:
                  if (curChar == 45)
                     jjAddStates(7, 11);
                  break;
               case 61:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(62, 64);
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(62, 63);
                  break;
               case 66:
                  if (curChar == 45)
                     jjCheckNAdd(67);
                  break;
               case 67:
                  if ((0x83ffe40000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjCheckNAdd(67);
                  break;
               case 68:
                  if ((0x83ffe40000000000L & l) == 0L)
                     break;
                  if (kind > 88)
                     kind = 88;
                  jjCheckNAddStates(0, 3);
                  break;
               case 69:
                  if ((0x83ffe40000000000L & l) == 0L)
                     break;
                  if (kind > 88)
                     kind = 88;
                  jjCheckNAdd(69);
                  break;
               case 70:
                  if ((0x83ffe40000000000L & l) == 0L)
                     break;
                  if (kind > 89)
                     kind = 89;
                  jjCheckNAdd(70);
                  break;
               case 71:
                  if ((0x83ffe40000000000L & l) != 0L)
                     jjCheckNAddTwoStates(71, 72);
                  break;
               case 72:
                  if (curChar == 61)
                     jjCheckNAdd(73);
                  break;
               case 73:
                  if ((0x83ffe40000000000L & l) == 0L)
                     break;
                  if (kind > 90)
                     kind = 90;
                  jjCheckNAddTwoStates(73, 74);
                  break;
               case 74:
                  if (curChar == 44)
                     jjCheckNAdd(75);
                  break;
               case 75:
                  if ((0x83ffe40000000000L & l) != 0L)
                     jjCheckNAddTwoStates(75, 76);
                  break;
               case 76:
                  if (curChar == 61)
                     jjCheckNAdd(77);
                  break;
               case 77:
                  if ((0x83ffe40000000000L & l) == 0L)
                     break;
                  if (kind > 90)
                     kind = 90;
                  jjCheckNAddTwoStates(74, 77);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 78:
                  if ((0x17fffffeaffffffeL & l) != 0L)
                     jjCheckNAddTwoStates(71, 72);
                  if ((0x17fffffeaffffffeL & l) != 0L)
                  {
                     if (kind > 89)
                        kind = 89;
                     jjCheckNAdd(70);
                  }
                  if ((0x17fffffeaffffffeL & l) != 0L)
                  {
                     if (kind > 88)
                        kind = 88;
                     jjCheckNAdd(69);
                  }
                  break;
               case 2:
                  if ((0x17fffffeaffffffeL & l) != 0L)
                  {
                     if (kind > 88)
                        kind = 88;
                     jjCheckNAddStates(0, 3);
                  }
                  if (curChar == 109)
                     jjAddStates(12, 15);
                  else if (curChar == 122)
                     jjstateSet[jjnewStateCnt++] = 12;
                  else if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 7;
                  else if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 4;
                  else if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 0:
                  if (curChar == 103 && kind > 84)
                     kind = 84;
                  break;
               case 1:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 3:
                  if (curChar == 109 && kind > 84)
                     kind = 84;
                  break;
               case 4:
               case 9:
                  if (curChar == 117)
                     jjCheckNAdd(3);
                  break;
               case 5:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 118 && kind > 84)
                     kind = 84;
                  break;
               case 7:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 10:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if (curChar == 122)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 15:
                  if ((0x17fffffeaffffffeL & l) == 0L)
                     break;
                  if (kind > 91)
                     kind = 91;
                  jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 16:
                  if (curChar == 109)
                     jjAddStates(12, 15);
                  break;
               case 17:
                  if (curChar == 110 && kind > 84)
                     kind = 84;
                  break;
               case 18:
               case 21:
                  if (curChar == 105)
                     jjCheckNAdd(17);
                  break;
               case 19:
                  if (curChar == 120 && kind > 84)
                     kind = 84;
                  break;
               case 20:
               case 25:
                  if (curChar == 97)
                     jjCheckNAdd(19);
                  break;
               case 22:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 23:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 26:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 32:
                  if ((0x8211000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 34:
                  if (curChar == 103 && kind > 86)
                     kind = 86;
                  break;
               case 35:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 36:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if (curChar == 109 && kind > 86)
                     kind = 86;
                  break;
               case 38:
               case 43:
                  if (curChar == 117)
                     jjCheckNAdd(37);
                  break;
               case 39:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if (curChar == 118 && kind > 86)
                     kind = 86;
                  break;
               case 41:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 42:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 44:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 45:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 47:
                  if (curChar == 122)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 48:
                  if (curChar == 109)
                     jjAddStates(16, 19);
                  break;
               case 49:
                  if (curChar == 110 && kind > 86)
                     kind = 86;
                  break;
               case 50:
               case 53:
                  if (curChar == 105)
                     jjCheckNAdd(49);
                  break;
               case 51:
                  if (curChar == 120 && kind > 86)
                     kind = 86;
                  break;
               case 52:
               case 57:
                  if (curChar == 97)
                     jjCheckNAdd(51);
                  break;
               case 54:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 58:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 59:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 60:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 63:
                  if ((0x8211000000000L & l) != 0L && kind > 85)
                     kind = 85;
                  break;
               case 64:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 65:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 67:
                  if ((0x17fffffeaffffffeL & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 68:
                  if ((0x17fffffeaffffffeL & l) == 0L)
                     break;
                  if (kind > 88)
                     kind = 88;
                  jjCheckNAddStates(0, 3);
                  break;
               case 69:
                  if ((0x17fffffeaffffffeL & l) == 0L)
                     break;
                  if (kind > 88)
                     kind = 88;
                  jjCheckNAdd(69);
                  break;
               case 70:
                  if ((0x17fffffeaffffffeL & l) == 0L)
                     break;
                  if (kind > 89)
                     kind = 89;
                  jjCheckNAdd(70);
                  break;
               case 71:
                  if ((0x17fffffeaffffffeL & l) != 0L)
                     jjCheckNAddTwoStates(71, 72);
                  break;
               case 73:
                  if ((0x17fffffeaffffffeL & l) == 0L)
                     break;
                  if (kind > 90)
                     kind = 90;
                  jjCheckNAddTwoStates(73, 74);
                  break;
               case 75:
                  if ((0x17fffffeaffffffeL & l) != 0L)
                     jjAddStates(20, 21);
                  break;
               case 77:
                  if ((0x17fffffeaffffffeL & l) == 0L)
                     break;
                  if (kind > 90)
                     kind = 90;
                  jjCheckNAddTwoStates(74, 77);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 78 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   69, 70, 71, 72, 30, 31, 32, 36, 39, 42, 47, 48, 18, 20, 24, 28, 
   50, 52, 56, 60, 75, 76, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, 
"\111\104\105\116\124\111\124\131", "\110\105\111\115\104\101\114\114\137\124\117\124\101\114\101\126\101", 
"\110\105\111\115\104\101\114\114", "\123\125\115", "\123\125\115\137\126", "\104\111\126\111\104\105", 
"\104\111\126\111\104\105\137\126", "\104\111\106\106", "\104\111\106\106\137\126", 
"\115\125\114\124\111\120\114\131", "\123\103\101\114\105", "\123\103\101\114\105\137\126", 
"\123\103\101\114\105\137\115\101\124\103\110", "\101\126\105\122\101\107\105", "\111\116\124\105\107\122\101\114", 
"\104\105\122\111\126\101\124\111\126\105", "\115\111\116", "\115\101\130", 
"\101\126\105\122\101\107\105\102\105\114\117\127", "\120\105\122\103\105\116\124\111\114\105", 
"\115\117\126\111\116\107\101\126\105\122\101\107\105", "\132\105\122\117\111\106\115\111\123\123\111\116\107\123\125\115", 
"\101\102\123\117\114\125\124\105", "\101\114\111\101\123", "\116\117\122\115\101\114\111\132\105", 
"\116\117\122\115\101\114\111\132\105\137\126", "\125\116\111\117\116", "\103\117\125\116\124", "\107\122\117\125\120", 
"\101\102\117\126\105", "\102\105\114\117\127", "\120\122\117\120\101\107\101\124\105", 
"\115\117\126\111\116\107", "\105\130\103\114\125\104\105", "\111\116\103\114\125\104\105", 
"\110\111\107\110\105\123\124", "\114\117\127\105\123\124", "\114\111\115\111\124", "\122\101\116\107\105", 
"\106\111\114\114", "\106\111\114\114\137\103\101\114\103\125\114\101\124\105", 
"\106\111\114\124\105\122", "\114\117\107", "\103\125\114\114\137\101\102\117\126\105", 
"\103\125\114\114\137\102\105\114\117\127", "\123\117\122\124", "\120\71\60", "\123\110\111\106\124", 
"\104\117\127\116\123\101\115\120\114\105", "\104\105\126\111\101\124\111\117\116", "\112\117\111\116", 
"\103\117\116\123\105\103\125\124\111\126\105", "\146\157\162\145\141\143\150", 
"\110\127\137\106\117\122\105\103\101\123\124", "\110\127\137\104\105\126\111\101\124\111\117\116", "\72", "\54", "\173", 
"\175", "\50", "\51", null, null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffffffffff800001L, 0xfffffffL, 
};
static final long[] jjtoSkip = {
   0x1eL, 0x0L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[78];
private final int[] jjstateSet = new int[156];
protected char curChar;
/** Constructor. */
public MetricReaderTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public MetricReaderTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 78; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100000400L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
